name: CICD for Youtube

on:
  push:
    branches:
        - main    #Turn On the deploy.yml whener someone make changes or push code to main branch

jobs: #We have to write two jobs i.e. Build and Deploy 
  build: #1 First Job oof Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2 #GitHub Inbuild Git Action
      - name: Use node js #For our reference
        uses: actions/setup-node@v1 #Github Action provides Node Environment
        with:
         node-version: ${{ matrix.node-version }} #Fetch Version form Line 13
      - name: npm install and build
        run: | #Pipe used for multiple commands
          npm install
          npm run build

        env: 
          CI: true   


  depoly: #2 Deploy Should happen only after successful Build
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master #For SSH deploy
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: | #Commands which we want to run on the Server
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh

               nvm instal 14
               npm install -g pm2
               cd ~/Actions-CICD-Youtube
               git pull origin main
               npm install
               npm run build
               pm2 restart api
            

#Line-47: Production Process Manager for Node. js applications that has a built-in load balancer.
#PM2 enables you to keep applications alive forever, reloads them without downtime, 
#Helps you to manage application logging, monitoring, and clustering.
#Git Actions, Authozied Key Modified with private key